### PR TITLE
Feature/credit earn crypto

### PR DESCRIPTION
**Pull request by this-kramer**
## Reason for this PR:

- We need the cryptographic credit-earn protocol

## Changes in this PR:

- Add credit-earn
- Adapt token, add generators
- Change workflow to use develop of craco and math

## Checklist:

Select whatever applies:

- [x] Test written
- [x] Code Properly Formatted
- [x] Documented
- [x] Changelog updated

### CODE REVIEW

**Review by JanBobolz — APPROVED** [review]
Look _great_ to me. Good job!

I can't reproduce the insane performance issues you seem to have had. The `CreditEarnTest` finishes in under 13 seconds on my machine, which is not fast by any means, but I'd say it's completely fine for now. 

If you want to optimize, spinkle in some `compute()` calls to enable concurrent computation of group operations. 
However, from the flame graph it looks like mostly the performance bottleneck is SPSEQ verification. We can optimize that a bit on our end. But most performance will come from switching to mcl (because our Java pairing is admittedly slow).

**Comment by this-kramer** [comment]
> Look _great_ to me. Good job!
> 
> I can't reproduce the insane performance issues you seem to have had. The `CreditEarnTest` finishes in under 13 seconds on my machine, which is not fast by any means, but I'd say it's completely fine for now.
> 
> If you want to optimize, spinkle in some `compute()` calls to enable concurrent computation of group operations.
> However, from the flame graph it looks like mostly the performance bottleneck is SPSEQ verification. We can optimize that a bit on our end. But most performance will come from switching to mcl (because our Java pairing is admittedly slow).

Thanks! Since the test case has more verification calls than a usual workflow, this should not be such a huge problem. Can you maybe give me some hints where using a compute call would be reasonable?

**Comment by JanBobolz** [comment]
> Can you maybe give me some hints where using a compute call would be reasonable?

In general, I'd recommend running `compute()` on any group element on which there won't be any more operations for a while (or ever). 

For example, `token.getC1().pow(s)` and `token.getC2().pow(s)` in `generateEarnRequest()` I would replace with `token.getC1().pow(s).compute()` and `token.getC2().pow(s).compute()`. 
After the `generateEarnRequest` call, I guess the request will usually just serialized, so at that point, the values will have to be computed anyway. Potentially small speedup through `compute()`, but why not have the exponentiation with s computed concurrently?

Same thing at the end of `handleEarnRequestResponse()`. 

But yeah. As I look closer, it actually seems to be the case that in this code, there are not actually as many `compute()` opportunities as I had blindly thought. Carry on 😉

**Comment by this-kramer** [comment]
> > Can you maybe give me some hints where using a compute call would be reasonable?
> 
> In general, I'd recommend running `compute()` on any group element on which there won't be any more operations for a while (or ever).
> 
> For example, `token.getC1().pow(s)` and `token.getC2().pow(s)` in `generateEarnRequest()` I would replace with `token.getC1().pow(s).compute()` and `token.getC2().pow(s).compute()`.
> After the `generateEarnRequest` call, I guess the request will usually just serialized, so at that point, the values will have to be computed anyway. Potentially small speedup through `compute()`, but why not have the exponentiation with s computed concurrently?
> 
> Same thing at the end of `handleEarnRequestResponse()`.
> 
> But yeah. As I look closer, it actually seems to be the case that in this code, there are not actually as many `compute()` opportunities as I had blindly thought. Carry on

I added some computes and rearranged the test case to allow more reasonable metrics. According to the logs, the protocol needs 8 seconds using representations.
```

**Pull request merged**
