### PR TITLE
Feature/dsprotection

### PR DESCRIPTION
**Pull request by pschuermann97**
## Reason for this PR:

- implemented version 1 of double-spending protection service + wrote unit tests for handlers

## Changes in this PR:

- handlers on DB side that provide functionality of double-spending protection service (see changelog for details)
- client-side request methods for the above functionality
- dbSync algo. implemented according to 2020 incentive system paper
- Link, Trace, VerifyDs implemented according to above paper
- minimal running example of deduct service implemented (see issue list for open problems)

## Checklist:

Select whatever applies:

- [x] Test written
- [x] Code Properly Formatted
- [x] Documented
- [x] Changelog updated

### CODE REVIEW

**Comment by feidens** [comment]
How thorough should the review be?

**Comment by JanBobolz** [comment]
> How thorough should the review be?

From the meeting: Only review if you want to. 
Also, I think we want to wait until merge conflicts have been solved.

**Comment by JanBobolz** [comment]
Rerequest review when conflicts have been solved.

**Comment by this-kramer** [comment]
> Rerequest review when conflicts have been solved.

I think there will be a new PR anyways since @pschuermann97 moved to a new branch :+1:

**Pull request closed without merging**
